### ISSUE TITLE
Meetup API key is in the repo

### ISSUE THREAD

**Issue by RobinDaugherty** [cincinnatirb/cincyrb#38]
The `.env` file was checked in, and the `.env.sample` file is different.

- The Meetup API key should be removed from the project.
- The API key should be regenerated on Meetup and the new key added in production.
- The `.env` file should be removed from the project.
- The pattern `.env*` should be added to `.gitignore`.
- The list of environment variables should be documented in the Readme file (and does not include `PORT`, which is not specific to this project).

**Comment by agilous** [comment]
The Meetup integration no longer requires and API key and the old key is no longer valid.
